---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-config
  namespace: source
data:
  schema: |
    {
      "namespace": "io.confluent.examples.clients.basicavro",
      "type": "record",
      "name": "Payment",
      "fields": [
        {"name": "id", "type": "string"},
        {"name": "amount", "type": "double"},
        {"name": "email", "type": "string"}
      ]
    }

---
apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: payment-value
  namespace: source
spec:
  data:
    configRef: schema-config
    format: avro
