---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm2
  template:
    metadata:
      labels:
        app: mm2
    spec:
      containers:
      - name: kconnect
        # image: confluentinc/cp-server-connect:7.9.0
        # Note: There is https://issues.apache.org/jira/browse/KAFKA-18007 causing issues with initial consumer group fetch 
        #       since AK 3.9.0 (with a fix in 4.0.0). We are using an older image to avoid this.
        image: confluentinc/cp-server-connect:7.8.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
        env:
        - name: KAFKA_LOG4J_OPTS
          value: "-Dlog4j.configuration=file:/mnt/config/log4j.properties"
        command: ['/bin/sh','-xc']
        args: ['/usr/bin/connect-mirror-maker /mnt/config/mm2.properties']
      volumes:
        - name: config-volume
          configMap:
            name: mm2-config
