---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm2
  template:
    metadata:
      labels:
        app: mm2
    spec:
      containers:
        - name: kconnect
          image: confluentinc/cp-server-connect:7.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/config
            - name: secret-volume
              mountPath: /mnt/secrets
          env:
            - name: KAFKA_LOG4J_OPTS
              value: "-Dlog4j.configuration=file:/mnt/config/log4j.properties"
            - name: EXTRA_ARGS
              value: "-javaagent:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.18.0.jar=7778:/mnt/config/jmx-exporter.yaml"
          command: ["/bin/sh", "-xc"]
          args: ["/usr/bin/connect-mirror-maker /mnt/config/mm2.properties"]
      volumes:
        - name: config-volume
          configMap:
            name: mm2-config
        - name: secret-volume
          secret:
            secretName: mm2-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mm2-rest
spec:
  selector:
    app: mm2
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
