apiVersion: v1
kind: Secret
metadata:
  name: mm2-secret
type: Opaque
stringData:
  mm2-credentials.txt: |
    src.bootstrap=kafka.source.svc.cluster.local:9092
    src.username=kafka
    src.password=kafka-secret
    dst.bootstrap=kafka.destination.svc.cluster.local:9092
    dst.username=kafka
    dst.password=kafka-secret
