apiVersion: v1
kind: Secret
metadata:
  name: credential
  namespace: kraft
type: Opaque
stringData:
  digest.txt: |
    username="kafka" 
    password="kafka-secret"
  plain-users.json: |
    {                                                                                                               
     "kafka_client": "kafka_client-secret",                                                                                          
     "c3": "c3-secret",                                                                                                              
     "kafka": "kafka-secret"                                                                                                         
    }                                                                                                                                 
  plain.txt: |
    username=kafka                                                                                                         
    password=kafka-secret                                                                                                             
  digest-users.json: |
    {                                                                                                              
      "kafka": "kafka-secret"                                                                                                         
    }
