---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: dc1
spec:
  podTemplate:
    labels:
      version: '1.0.0'
      ingress-group: zk1
  replicas: 3
  oneReplicaPerNode: true
  image:
    application: confluentinc/cp-zookeeper:7.7.1
    init: confluentinc/confluent-init-container:2.9.3
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  logVolumeCapacity: 1Gi
  configOverrides:
    jvm:
      - -Dzookeeper.multiAddress.enabled=true
    server:
      - 4lw.commands.whitelist=*
    peers:
      - server.0=zookeeper-0.zookeeper.dc1:2888:3888|zk0-proxy.bridge:2888:3888
      - server.1=zookeeper-1.zookeeper.dc1:2888:3888|zk1-proxy.bridge:2888:3888
      - server.2=zookeeper-2.zookeeper.dc1:2888:3888|zk2-proxy.bridge:2888:3888
      # - server.10=zookeeper-0.zookeeper.dc2:2888:3888|zk10-proxy.bridge:2888:3888
      # - server.11=zookeeper-1.zookeeper.dc2:2888:3888|zk11-proxy.bridge:2888:3888
      # - server.12=zookeeper-2.zookeeper.dc2:2888:3888|zk12-proxy.bridge:2888:3888
      - server.10=zk10-proxy.bridge:2888:3888
      - server.11=zk11-proxy.bridge:2888:3888
      - server.12=zk12-proxy.bridge:2888:3888
      - server.99=zookeeperobserver.zookeeper.dc1:2888:3888:observer|zookeeperobserver.zookeeper.dc1:2888:3888:observer
      - group.0=0:1:2
      - group.1=10:11:12
      - group.99=99
      - weight.0=1
      - weight.1=1
      - weight.2=1
      - weight.10=1
      - weight.11=1
      - weight.12=1
      - weight.99=0