---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: replicator-pull
  namespace: destination
spec:
  class: io.confluent.connect.replicator.ReplicatorSourceConnector
  taskMax: 1
  configs:
    header.converter: io.confluent.connect.replicator.util.ByteArrayConverter
    key.converter: io.confluent.connect.replicator.util.ByteArrayConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schemas.enable: "true"
    value.converter.schema.registry.url: http://schemaregistry.destination.svc.cluster.local:8081
    # value.converter.basic.auth.credentials.source: USER_INFO
    # value.converter.schema.registry.basic.auth.user.info: user:password
    # topic.whitelist: test-topic
    # topic.blacklist: doNotReplicate
    topic.regex: ^test-.*
    topic.rename.format: ${topic}.replicated
    topic.auto.create: "false"
    src.kafka.bootstrap.servers: kafka.source.svc.cluster.local:9092
    # src.kafka.security.protocol: SASL_SSL
    # src.kafka.sasl.mechanism: PLAIN
    # src.kafka.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username=\"REDACTED\" password=\"REDACTED\"
    src.value.converter: org.apache.kafka.connect.json.JsonConverter
    src.value.converter.schemas.enable: "false"
