apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink
  namespace: source
spec:
  destinationKafkaCluster:
    bootstrapEndpoint: kafka.destination.svc.cluster.local:9092
    kafkaRestClassRef: 
      name: kafka-rest
      namespace: destination
  sourceKafkaCluster:
    bootstrapEndpoint: kafka.source.svc.cluster.local:9092
    kafkaRestClassRef: 
      name: kafka-rest
      namespace: source
  mirrorTopics:
  - name: test-topic
