---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: destination
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  logVolumeCapacity: 1Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: destination
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  dependencies:
    zookeeper:  
      endpoint: zookeeper.destination.svc.cluster.local:2181
  configOverrides:
    server:
      - offsets.topic.replication.factor=1
      - password.encoder.secret=encoder-secret
      - transaction.state.log.replication.factor=1
      - confluent.license.topic.replication.factor=1
      - confluent.metadata.topic.replication.factor=1
      - confluent.balancer.topic.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.security.event.logger.exporter.kafka.topic.replicas=1
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: kafka-rest
  namespace: destination
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.destination.svc.cluster.local:8090
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: destination
spec:
  replicas: 1
  enableSchemaExporter: true
  image:
    application: confluentinc/cp-schema-registry:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  license:
    globalLicense: true
  dependencies:
    kafka:  
      bootstrapEndpoint: kafka.destination.svc.cluster.local:9071
