apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: source
spec:
  name: test-topic
  replicas: 3
  partitionCount: 6
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
    namespace: source
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic-1
  namespace: source
spec:
  name: test-topic-1
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
    namespace: source
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic-2
  namespace: source
spec:
  name: test-topic-2
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "compact"
    retention.ms: "3600000"
  kafkaClusterRef:
    name: kafka
    namespace: source