apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: source
spec:
  name: test-topic
  replicas: 1
  partitionCount: 6
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
    namespace: source